import * as THREE from 'three';
import {makeMemoryScenes} from './memory-scenes.js';
import{RoundedBoxGeometry}from'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import{ROOMS,CATALOG,clampPosition,interactionAt,stepToward}from'./navigation.mjs';
const $=s=>document.querySelector(s),canvas=$('#world'),mobile=()=>innerWidth<900,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let renderer,scene,camera,street,interior,avatar,legs=[],arms=[],lanterns=[],clock,room=null,target=null,pendingRoom=null,transitioning=false,interaction=null,lastTime=0,walkPhase=0,visited=new Set(),frameId,doorTargets=[],roomTargets=[];
let memories={};
const roomBase=()=>room?.base||0;
const keys=new Set(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),position={x:0,z:5.2};
function material(color,roughness=.85,metalness=0,emissive=null){return new THREE.MeshStandardMaterial({color,roughness,metalness,...(emissive?{emissive,emissiveIntensity:1.3}:{})})}
const M={wall:material('#304346'),plaster:material('#5e6a61'),darkwall:material('#243236'),wood:material('#302925'),woodLight:material('#79573b'),trim:material('#a48754',.45,.35),roof:material('#263c3c',.75,.12),roofEdge:material('#45635b',.6,.1),stone:material('#71817c',.55),road:material('#3e5051',.38,.18),glass:material('#e5b26b',.4,0,'#bc6928'),paper:material('#eec480',.65,0,'#ea8e36'),red:material('#774d34'),green:material('#476c5b'),leaf:material('#405b46'),black:material('#171f21'),cream:material('#d5c6a0'),coat:material('#ad8862'),hair:material('#292827'),skin:material('#d8b58d'),pants:material('#243e3e'),brass:material('#ae975c',.35,.55),floor:material('#624d39',.6)};
const boxGeo=new THREE.BoxGeometry(1,1,1),sphereGeo=new THREE.SphereGeometry(1,16,12);
function mesh(geo,mat,parent,x=0,y=0,z=0){const o=new THREE.Mesh(geo,mat);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function box(parent,x,y,z,w,h,d,mat,round=0){const o=mesh(round?new RoundedBoxGeometry(w,h,d,2,round):boxGeo,mat,parent,x,y,z);if(!round)o.scale.set(w,h,d);return o}
function ball(parent,x,y,z,sx,sy,sz,mat){const o=mesh(sphereGeo,mat,parent,x,y,z);o.scale.set(sx,sy,sz);return o}
function cyl(parent,x,y,z,r,h,mat,r2=r,segments=16){return mesh(new THREE.CylinderGeometry(r2,r,h,segments),mat,parent,x,y,z)}
function line(parent,pts,r,mat){return mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts.map(p=>new THREE.Vector3(...p))),Math.max(8,pts.length*5),r,6,false),mat,parent)}
function group(parent,x=0,y=0,z=0){const g=new THREE.Group();g.position.set(x,y,z);parent.add(g);return g}
function sign(parent,text,x,y,z,w,h,{bg='#1f3332',fg='#dcc896',vertical=false,size=85}={}){const c=document.createElement('canvas');c.width=vertical?256:1024;c.height=vertical?1024:256;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle=fg;ctx.lineWidth=3;ctx.globalAlpha=.45;ctx.strokeRect(12,12,c.width-24,c.height-24);ctx.strokeRect(20,20,c.width-40,c.height-40);ctx.globalAlpha=1;ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${vertical?155:size}px "Songti SC","Noto Serif CJK SC",serif`;if(vertical){[...text].forEach((ch,i)=>ctx.fillText(ch,c.width/2,170+i*200))}else{ctx.fillText(text,c.width/2,c.height/2+5)}const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const mat=new THREE.MeshStandardMaterial({map:tex,roughness:.8,emissive:'#998251',emissiveIntensity:.12});return mesh(new THREE.PlaneGeometry(w,h),mat,parent,x,y,z)}
function lantern(parent,x,y,z,scale=1){const g=group(parent,x,y,z);g.scale.setScalar(scale);line(g,[[0,.55,0],[0,.9,0],[.2,1,0]],.025,M.black);ball(g,0,0,0,.26,.38,.26,M.paper);cyl(g,0,.34,0,.20,.075,M.brass);cyl(g,0,-.34,0,.17,.075,M.brass);for(let i=0;i<8;i++){const a=i*Math.PI/4;line(g,[[Math.cos(a)*.12,-.34,Math.sin(a)*.12],[Math.cos(a)*.26,0,Math.sin(a)*.26],[Math.cos(a)*.16,.34,Math.sin(a)*.16]],.009,M.woodLight)}line(g,[[0,-.39,0],[0,-.64,0]],.016,M.red);ball(g,0,-.66,0,.045,.11,.045,M.red);lanterns.push({o:g,phase:x*4+y});return g}
function windowFrame(parent,x,y,z,w=1,h=1.6){box(parent,x,y,z,w+.13,h+.13,.14,M.wood);box(parent,x,y,z+.08,w,h,.055,M.glass);for(let i=-1;i<=1;i++)box(parent,x+i*w/3,y,z+.13,.035,h,.035,M.wood);for(let i=-2;i<=2;i++)box(parent,x,y+i*h/5,z+.13,w,.035,.035,M.wood);box(parent,x,y+h*.22,z+.17,w,.075,.045,M.wood)}
function roof(parent,x,y,z,w,d){const verts=[],indices=[],n=12;for(let i=0;i<=n;i++){const t=i/n*2-1;const yy=.65*(1-t*t)+.18*Math.pow(Math.abs(t),8);verts.push(x+t*w/2,y+yy,z-d/2,x+t*w/2,y+yy,z+d/2)}for(let i=0;i<n;i++){const j=i*2;indices.push(j,j+1,j+2,j+1,j+3,j+2)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.setIndex(indices);geo.computeVertexNormals();const mat=M.roof.clone();mat.side=THREE.DoubleSide;mesh(geo,mat,parent);for(let i=0;i<=20;i++){const t=i/20*2-1;const yy=.65*(1-t*t)+.18*Math.pow(Math.abs(t),8);line(parent,[[x+t*w/2,y+yy+.025,z-d/2],[x+t*w/2,y+yy+.025,z+d/2]],.027,M.roofEdge)}for(const zz of[z-d/2,z+d/2])line(parent,Array.from({length:17},(_,i)=>{const t=i/8-1;return[x+t*w/2,y+.65*(1-t*t)+.18*Math.abs(t)**8,zz]}),.075,M.roofEdge);line(parent,[[x,y+.67,z-d/2-.15],[x,y+.68,z+d/2+.15]],.075,M.roofEdge)}
function planter(parent,x,y,z,s=1){const g=group(parent,x,y,z);g.scale.setScalar(s);cyl(g,0,.26,0,.22,.52,M.woodLight,.34);cyl(g,0,.53,0,.35,.065,M.trim);for(let i=0;i<7;i++){const a=i*2.4;line(g,[[0,.5,0],[Math.cos(a)*.2,.9,Math.sin(a)*.2],[Math.cos(a)*.45,1.12+(i%3)*.12,Math.sin(a)*.45]],.023,M.green);const leaf=ball(g,Math.cos(a)*.33,1+(i%3)*.1,Math.sin(a)*.33,.12,.32,.065,M.leaf);leaf.rotation.z=-Math.cos(a)*.6;leaf.rotation.y=-a}}
function shop(r,index){if(r.id==='museum'){museumDoor(r);return;}const g=group(street,r.x,0,-2.5);const wall=index===1?M.darkwall:M.wall;box(g,0,2.65,-.8,6.3,5.3,4,wall);box(g,0,.16,1.6,6.45,.32,1.4,M.stone);box(g,0,.09,2.1,2,.18,.6,M.stone);for(const x of[-2.95,2.95]){box(g,x,2.25,1.23,.17,4.5,.2,M.wood);cyl(g,x,.4,1.3,.18,.5,M.stone)}box(g,0,3.08,1.29,6.3,.18,.22,M.wood);box(g,0,4.78,1.3,6.3,.16,.22,M.wood);for(let j=0;j<7;j++)box(g,-2.8+j*.94,4.05,1.23,.075,1.4,.12,M.wood);
 // Recessed doorway and openable-looking timber doors.
 box(g,0,1.47,1.27,1.65,2.55,.12,M.black);for(const x of[-.83,.83])box(g,x,1.47,1.43,.13,2.7,.18,M.woodLight);box(g,0,2.8,1.44,1.85,.13,.18,M.woodLight);for(const side of[-1,1]){const d=box(g,side*.47,1.4,1.38,.77,2.45,.08,M.wood);box(g,side*.47,1.9,1.44,.55,1.08,.04,M.glass);for(let j=0;j<4;j++)box(g,side*.47,1.48+j*.23,1.47,.55,.035,.04,M.wood);ball(g,side*.12,1.2,1.53,.044,.044,.044,M.brass);box(g,side*.47,.67,1.46,.58,.6,.07,M.woodLight)}
 for(const x of[-2,2]){windowFrame(g,x,1.72,1.35,1.05,1.7);box(g,x,.53,1.37,1.23,.10,.26,M.woodLight)}for(const x of[-1.6,1.6])windowFrame(g,x,3.98,1.32,1.7,1.05);
 box(g,0,3.1,1.65,2.8,.64,.2,M.wood);sign(g,r.name,0,3.1,1.76,2.63,.49,{size:90,bg:index===2?'#264139':'#2c2922'});roof(g,0,3.55,1.35,6.85,1.5);roof(g,0,5.25,-.65,6.95,5.15);
 for(const x of[-1.32,1.32])lantern(g,x,2.74,1.99,.8);sign(g,r.symbol,2.86,2.36,1.65,.44,1.52,{vertical:true,bg:index===2?'#294b41':'#653c2a'});
 const light=new THREE.PointLight('#ffc585',20,7,2);light.position.set(0,2.35,2.9);g.add(light);planter(g,-2.7,.26,2.0,.75);planter(g,2.75,.2,2.05,.7);
 const door=box(g,0,1.4,1.6,1.75,2.8,.14,new THREE.MeshBasicMaterial({visible:false}));door.userData.room=r.id;doorTargets.push(door);
 // Little pavement menu board.
 const board=group(g,2,.35,2.4);board.rotation.y=-.18;box(board,0,.44,0,.66,.84,.09,M.woodLight);sign(board,index===0?'茶 · 光':index===1?'今夜有约':'收 · 支',0,.48,.051,.55,.65,{size:100});for(const x of[-.25,.25])box(board,x,.03,0,.05,.75,.06,M.wood);
}
function museumDoor(r){const g=group(street,r.x,0,-2.5),stone=material('#aaac9d');box(g,0,2,-.7,6.2,4,4,stone);box(g,0,3.6,.9,6.7,1.5,1.5,stone);box(g,0,.18,1.8,6.8,.3,2,M.stone);for(let x=-2.8;x<3;x+=.36)box(g,x,3.6,1.66,.018,1.46,.02,M.stone);box(g,0,1.5,1.35,2.2,2.6,.1,M.black);for(const x of[-2,2])windowFrame(g,x,1.8,1.36,1.15,2.15);sign(g,'木 心 美 术 馆',0,3.45,1.7,4.2,.55,{bg:'#aaac9d',fg:'#354941',size:95});for(const x of[-.95,.95])box(g,x,1.4,1.5,.06,2.5,.06,M.trim);box(g,0,2.6,1.5,2,.045,.07,M.paper);const door=box(g,0,1.4,1.6,2.2,2.8,.14,new THREE.MeshBasicMaterial({visible:false}));door.userData.room=r.id;doorTargets.push(door);const light=new THREE.PointLight('#eddbb0',25,8,2);light.position.set(0,2,2.7);g.add(light);}
function makeStreet(){street=group(scene);box(street,0,-.20,0,70,.35,70,M.road);box(street,0,-.06,-2.5,37,.18,7,M.stone);
 // Instanced irregular stone paving keeps the mobile scene light.
 const n=47*16,geo=new RoundedBoxGeometry(.71,.08,.40,1,.025),stones=new THREE.InstancedMesh(geo,M.road,n),dummy=new THREE.Object3D(),col=new THREE.Color();let k=0;
 for(let z=0;z<16;z++)for(let x=0;x<47;x++){dummy.position.set((x-23)*.77+(z%2)*.38,-.012,z*.47+.35);dummy.rotation.y=Math.sin(x*43+z*3)*.02;dummy.updateMatrix();stones.setMatrixAt(k,dummy.matrix);col.setHSL(.49,.10,.22+((Math.sin(x*37+z*21)+1)/2)*.10);stones.setColorAt(k++,col)}stones.receiveShadow=true;street.add(stones);
 ROOMS.forEach(shop);
 // Dark buildings recede into the mist beyond the little street.
 for(const side of[-1,1])for(let i=0;i<3;i++){box(street,side*(21+i*6),3+i*.2,-4-i*2,5,6+i*.4,6,M.darkwall);roof(street,side*(21+i*6),6+i*.4,-4-i*2,5.6,6.6);for(const xx of[-1,1])windowFrame(street,side*(21+i*6)+xx,3.5,-.9-i*2,.8,1.3)}
 // Amber lamps and a low curb frame the foreground.
 for(const x of[-10.5,10.5]){cyl(street,x,1.8,4.1,.05,3.6,M.black);cyl(street,x,.15,4.1,.22,.3,M.black);line(street,[[x,3.6,4.1],[x,4,4.1],[x+.65,4.07,4.1]],.046,M.black);lantern(street,x+.65,3.32,4.1,.9)}
 for(let i=0;i<50;i++)box(street,(i-25)*.72,-.005,8.2,.67,.22,.27,M.stone);
 // Bench, forgotten bicycle, stools, and scattered brass highlights.
 const bench=group(street,-4,.0,1.1);for(let i=0;i<4;i++)box(bench,0,.45,i*.12,1.65,.06,.085,M.woodLight);for(const x of[-.62,.62])for(const z of[0,.4])box(bench,x,.23,z,.07,.45,.07,M.black);
 const bike=group(street,9.8,.56,.7);bike.rotation.y=-.45;for(const x of[-.48,.48]){const wheel=mesh(new THREE.TorusGeometry(.32,.023,7,28),M.black,bike,x,0,0);for(let i=0;i<8;i++)line(bike,[[x,0,0],[x+.31*Math.sin(i*Math.PI/4),.31*Math.cos(i*Math.PI/4),0]],.004,M.stone)}for(const[a,b]of[[[-.48,0,0],[-.25,.46,0]],[[-.25,.46,0],[.03,0,0]],[[.03,0,0],[-.48,0,0]],[[-.25,.46,0],[.32,.47,0]],[[.32,.47,0],[.03,0,0]],[[.32,.47,0],[.48,0,0]]])line(bike,[a,b],.023,M.green);box(bike,-.25,.50,0,.24,.05,.1,M.wood);line(bike,[[.32,.47,0],[.29,.67,0],[.43,.67,0]],.018,M.stone);
 // Floating dust catches lantern light, without obscuring the view.
 const particleGeo=new THREE.BufferGeometry(),p=[];for(let i=0;i<100;i++)p.push(Math.sin(i*127)*15,1+(i%23)*.25,Math.cos(i*61)*8);particleGeo.setAttribute('position',new THREE.Float32BufferAttribute(p,3));const dust=new THREE.Points(particleGeo,new THREE.PointsMaterial({color:'#d5b776',size:.022,transparent:true,opacity:.45,depthWrite:false}));street.add(dust);street.userData.dust=dust;
}
function mug(parent,x,y,z){cyl(parent,x,y,z,.07,.13,M.cream);const ring=mesh(new THREE.TorusGeometry(.044,.013,6,12),M.cream,parent,x+.075,y,z);ring.rotation.y=0;cyl(parent,x,y+.069,z,.058,.005,M.wood)}
function makeRoom(){interior=group(scene,60,0,0);interior.visible=false;box(interior,0,-.12,0,9,.24,9,M.floor);for(let x=-4;x<=4;x+=.45)box(interior,x,.009,0,.016,.01,9,M.wood);box(interior,0,2.25,-3.7,9,4.5,.25,M.darkwall);box(interior,-4.35,2.25,0,.22,4.5,7.5,M.wall);box(interior,4.35,.48,0,.22,.96,7.5,M.wall);
 for(const x of[-4.25,0,4.25])box(interior,x,2.25,-3.48,.16,4.5,.18,M.woodLight);for(const y of[.3,3.7])box(interior,0,y,-3.48,8.5,.13,.17,M.woodLight);
 const sideWindow=group(interior,-4.19,0,0);sideWindow.rotation.y=Math.PI/2;windowFrame(sideWindow,0,2,0,1.5,2.3);
 // A wall of small drawers evokes an old pawnshop without copying a show set.
 for(let i=0;i<7;i++)for(let j=0;j<4;j++){box(interior,-2.9+i*.94,.9+j*.53,-3.4,.85,.46,.37,M.wood);box(interior,-2.9+i*.94,.9+j*.53,-3.195,.65,.32,.06,M.woodLight);ball(interior,-2.9+i*.94,.9+j*.53,-3.135,.035,.035,.035,M.brass)}
 box(interior,0,.67,-1.7,4.6,1.34,.8,M.wood);box(interior,0,1.38,-1.68,4.9,.14,1.03,M.woodLight);for(const x of[-1.8,-.9,0,.9,1.8])box(interior,x,.68,-1.25,.73,.93,.045,M.trim);box(interior,0,.68,-1.20,4.3,.07,.045,M.wood);
 // Open paper menu, teapot and warm table lamps.
 const book=group(interior,.1,1.54,-1.5);book.rotation.x=-.40;for(const side of[-1,1]){const pg=box(book,side*.23,0,0,.44,.035,.62,M.cream);pg.rotation.z=side*.13;for(let i=0;i<5;i++)box(book,side*.23,.028,-.18+i*.08,.27,.008,.012,M.woodLight)}
 const menuTarget=box(interior,0,1.50,-1.4,2.2,.6,1.0,new THREE.MeshBasicMaterial({visible:false}));menuTarget.userData.action='menu';roomTargets.push(menuTarget);
 ball(interior,-1.5,1.63,-1.65,.18,.18,.16,M.green);cyl(interior,-1.5,1.81,-1.65,.10,.03,M.brass);line(interior,[[-1.37,1.6,-1.65],[-1.21,1.66,-1.65],[-1.18,1.72,-1.65]],.044,M.green);mug(interior,-.95,1.53,-1.56);mug(interior,-1.9,1.53,-1.56);
 for(const x of[-2.4,2.4])lantern(interior,x,3.3,-2,1.1);const warm=new THREE.PointLight('#ffd394',35,13,2);warm.position.set(0,3.5,0);interior.add(warm);
 sign(interior,'今 夜 菜 单',0,3.54,-3.25,2.4,.55,{size:95,bg:'#263631'});
 // Two intimate tables with seats, cups, carpets and shelves.
 for(const side of[-1,1]){const t=group(interior,side*2.9,0,1);cyl(t,0,.92,0,.68,.1,M.woodLight);cyl(t,0,.45,0,.08,.9,M.wood);cyl(t,0,.05,0,.3,.1,M.wood);mug(t,-.15,1.05,0);mug(t,.20,1.05,.1);for(const z of[-.9,.9]){cyl(t,0,.51,z,.3,.1,M.woodLight);for(const xx of[-.16,.16])for(const zz of[-.16,.16])box(t,xx,.25,z+zz,.045,.5,.045,M.wood)}}planter(interior,-3.75,.0,-2.8,1.4);planter(interior,3.75,.0,-2.8,1.4);
 box(interior,0,.014,2.4,2.2,.02,2.1,M.red);for(const x of[-.97,.97])box(interior,x,.027,2.4,.035,.01,1.9,M.trim);box(interior,0,.03,3.57,2.4,.035,.25,M.brass);
}
function makeAvatar(){avatar=group(scene);const coat=mesh(new RoundedBoxGeometry(.43,.56,.29,3,.10),M.coat,avatar,0,.89,0);box(avatar,0,.86,.153,.032,.39,.017,M.woodLight);for(let i=0;i<3;i++)ball(avatar,.07,1.03-i*.12,.161,.016,.016,.016,M.brass);ball(avatar,0,1.39,0,.21,.25,.2,M.skin);ball(avatar,0,1.52,-.025,.22,.17,.20,M.hair);for(const x of[-.085,.085])ball(avatar,x,1.42,.177,.018,.02,.012,M.black);ball(avatar,0,1.34,.2,.027,.038,.025,M.skin);cyl(avatar,0,1.66,-.01,.30,.04,M.green);cyl(avatar,0,1.74,-.01,.20,.15,M.green,.17);cyl(avatar,0,1.685,-.01,.206,.045,M.woodLight);box(avatar,0,1.20,.02,.41,.12,.34,M.red,.035);box(avatar,.13,1.04,.18,.11,.33,.05,M.red,.015);
 for(const side of[-1,1]){const leg=group(avatar,side*.13,.62,0);box(leg,0,-.23,0,.15,.46,.17,M.pants,.045);box(leg,0,-.47,.055,.18,.12,.29,M.black,.04);legs.push(leg);const arm=group(avatar,side*.28,1.13,0);box(arm,0,-.22,0,.14,.44,.17,M.coat,.04);ball(arm,0,-.46,.02,.07,.075,.07,M.skin);arms.push(arm)}
 // Soft contact shadow remains grounded even on low-end devices.
 const c=document.createElement('canvas');c.width=c.height=64;const ctx=c.getContext('2d'),gr=ctx.createRadialGradient(32,32,1,32,32,31);gr.addColorStop(0,'#00000080');gr.addColorStop(1,'#00000000');ctx.fillStyle=gr;ctx.fillRect(0,0,64,64);const shadow=mesh(new THREE.PlaneGeometry(.95,.95),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthWrite:false}),avatar,0,.025,0);shadow.rotation.x=-Math.PI/2;shadow.castShadow=false;
}
function setup(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile()?1.5:2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();scene.background=new THREE.Color('#11262b');scene.fog=new THREE.FogExp2('#11262b',.022);camera=new THREE.OrthographicCamera();camera.near=.1;camera.far=150;scene.add(new THREE.HemisphereLight('#a2c7d0','#443626',2));const moon=new THREE.DirectionalLight('#b3d6e1',2.8);moon.position.set(-8,16,8);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);Object.assign(moon.shadow.camera,{left:-18,right:18,top:14,bottom:-14,near:1,far:50});moon.shadow.bias=-.0006;moon.shadow.normalBias=.04;scene.add(moon);const roomLight=new THREE.DirectionalLight('#e9c88c',2);roomLight.position.set(64,8,4);roomLight.target.position.set(60,0,0);scene.add(roomLight,roomLight.target);makeStreet();makeRoom();memories=makeMemoryScenes(scene,{group,box,ball,cyl,sign,planter,M});makeAvatar();resize();clock=new THREE.Clock();animate();$('#loading').style.opacity=0;setTimeout(()=>$('#loading').hidden=true,550)}
function resize(){if(!renderer)return;renderer.setSize(innerWidth,innerHeight);const aspect=innerWidth/innerHeight;const height=mobile()?(room?11:16):(room?17:35)/aspect,width=height*aspect;camera.left=-width/2;camera.right=width/2;camera.top=height/2;camera.bottom=-height/2;camera.updateProjectionMatrix()}
function moveCamera(dt){const base=roomBase(),focus=room?base:position.x*.8;const look=new THREE.Vector3(focus,room?.9:1.25,room?-.4:.7);const desired=look.clone().add(room?new THREE.Vector3(7,10,15):new THREE.Vector3(9,13,22));camera.position.lerp(desired,lastTime===0?1:1-Math.exp(-dt*4));camera.lookAt(look)}
function animate(){frameId=requestAnimationFrame(animate);if(document.hidden){clock.getDelta();return}const dt=Math.min(clock.getDelta(),.04),t=clock.elapsedTime;let moving=false;if(!transitioning&&!$('#menu').open){let dx=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),dz=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);if(dx||dz){target=null;pendingRoom=null;const len=Math.hypot(dx,dz),next=clampPosition(position.x+dx/len*dt*2.6,position.z+dz/len*dt*2.6,!!room);moving=Math.hypot(next.x-position.x,next.z-position.z)>.0001;Object.assign(position,next);if(moving)avatar.rotation.y=Math.atan2(dx,dz)}else if(target){const next=stepToward(position,target,dt*3,!!room);moving=next.moving;if(moving)avatar.rotation.y=Math.atan2(target.x-position.x,target.z-position.z);Object.assign(position,{x:next.x,z:next.z});if(Math.hypot(position.x-target.x,position.z-target.z)<.08){target=null;if(pendingRoom){const id=pendingRoom;pendingRoom=null;enterRoom(id)}}}}
if(moving)walkPhase+=dt*9;legs.forEach((l,i)=>l.rotation.x=moving?Math.sin(walkPhase+i*Math.PI)*.55:THREE.MathUtils.damp(l.rotation.x,0,12,dt));arms.forEach((a,i)=>a.rotation.x=moving?-Math.sin(walkPhase+i*Math.PI)*.35:THREE.MathUtils.damp(a.rotation.x,0,12,dt));avatar.position.set(position.x+roomBase(),moving?Math.abs(Math.sin(walkPhase))*.035:0,position.z);if(!reduced){lanterns.forEach(({o,phase})=>o.rotation.z=Math.sin(t*.6+phase)*.025);street.userData.dust.position.y=Math.sin(t*.2)*.15}updateInteraction();moveCamera(dt);lastTime=t;renderer.render(scene,camera);canvas.dataset.ready='true';canvas.dataset.room=room?.id||'street';canvas.dataset.position=[position.x,position.z].map(v=>v.toFixed(2)).join(',')}
function updateInteraction(){const next=interactionAt(position.x,position.z,room?.id);if(JSON.stringify(next)!==JSON.stringify(interaction)){interaction=next;$('#action').disabled=!next;$('#action-label').textContent=next?.label||(room?'往前走，看看这里的故事':'走近一扇门');if(next)$('#hint').textContent=next.type==='enter'?'按 E 或点击按钮入店':['menu','memory'].includes(next.type)?'按 E 翻开眼前的故事':'按 E 或点击按钮返回街道';else $('#hint').textContent=room?(room.kind==='lounge'?'点击柜台上的书，或在屋里走走':'沿路向前，靠近故事后按 E 阅读'):'点击路面行走，或点击店门进入'}}
function transition(fn){if(transitioning)return;transitioning=true;keys.clear();target=null;$('#map-panel').hidden=true;$('#transition').classList.add('active');setTimeout(()=>{fn();resize();camera.position.set(roomBase()+7,11,18);setTimeout(()=>{$('#transition').classList.remove('active');transitioning=false},100)},reduced?0:350)}
function enterRoom(id){const r=ROOMS.find(r=>r.id===id);if(!r)return;if(r.destination){try{sessionStorage.setItem('lane-return',JSON.stringify({x:r.x,z:1.5}));}catch{}transition(()=>{window.location.assign(r.destination)});return;}transition(()=>{room=r;street.visible=false;interior.visible=r.kind==='lounge';for(const [id,g]of Object.entries(memories))g.visible=id===r.id;visited.add(id);position.x=0;position.z=2.45;avatar.rotation.y=Math.PI;$('#story').hidden=true;$('#room-label').hidden=false;$('#room-label h2').textContent=r.name;$('#room-label span').textContent=r.subtitle;$('#location').textContent=r.name+(r.kind==='mountains'?' · 营地':' · 室内');$('#leave').hidden=false;$('#menu-shortcut').hidden=false;$('#menu-shortcut').textContent=r.kind==='lounge'?'下一扇门 ↗':'读这里的故事 ↗';$('#menu-subtitle').textContent=r.subtitle;$('#hint').textContent=r.kind==='lounge'?'点击柜台上的书，或在屋里走走':'沿路向前，按 E 阅读；向后走可以回街上';interaction=undefined;updateInteraction()})}
function leaveRoom(){if(!room)return;transition(()=>{position.x=room.x;position.z=1.5;avatar.rotation.y=0;room=null;interior.visible=false;for(const g of Object.values(memories))g.visible=false;street.visible=true;$('#story').hidden=false;$('#room-label').hidden=true;$('#location').textContent='第八巷 · 街道';$('#leave').hidden=true;$('#menu-shortcut').hidden=true;interaction=undefined;updateInteraction()})}
function openMenu(){if(!room||transitioning)return;keys.clear();target=null;$('#memory-note').hidden=room.kind==='lounge';$('#world-doors').hidden=room.kind!=='lounge';$('#menu-title').textContent=room.kind==='travel'?'旅行册的第一页':room.kind==='mountains'?'山野来信':'下一扇门，去哪里？';$('#memory-copy').textContent=room.kind==='travel'?'这里为以后去过的城市、海边和路途留着位置。现在的相框还是空白；每一张照片到来，都可以变成一扇新的门。':'这里是一处想象中的山间营地。等写下真实山名、路线与照片，再把走过的山路搬进这个小世界。';$('#menu').showModal();$('#menu .close-menu').focus()}
function act(){if(!interaction)return;if(interaction.type==='enter')enterRoom(interaction.room);else if(['menu','memory'].includes(interaction.type))openMenu();else leaveRoom()}
function travel(id){const r=ROOMS.find(r=>r.id===id);if(!r||transitioning)return;if(room){leaveRoom();setTimeout(()=>travel(id),500);return}target={x:r.x,z:.8};pendingRoom=id;$('#map-panel').hidden=true;$('#hint').textContent='正走向'+r.name+'…'}
let press=null;canvas.addEventListener('pointerdown',e=>press={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(!press||Math.hypot(e.clientX-press.x,e.clientY-press.y)>12||transitioning||$('#menu').open)return;press=null;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(room?(room.kind==='lounge'?roomTargets:[]):doorTargets,false)[0];if(hit){if(room)openMenu();else travel(hit.object.userData.room);return}const floor=new THREE.Plane(new THREE.Vector3(0,1,0),0),pt=new THREE.Vector3();if(raycaster.ray.intersectPlane(floor,pt)){target=clampPosition(pt.x-roomBase(),pt.z,!!room);pendingRoom=null}});
window.addEventListener('keydown',e=>{if($('#menu').open)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key)}if(e.key.toLowerCase()==='e'&&!e.repeat)act();if(e.key==='Escape'){if(!$('#map-panel').hidden)$('#map-panel').hidden=true;else if(room)leaveRoom()}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>keys.clear());window.addEventListener('resize',resize);
document.querySelectorAll('[data-key]').forEach(btn=>{const clear=()=>keys.delete(btn.dataset.key);btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);keys.add(btn.dataset.key)});btn.addEventListener('pointerup',clear);btn.addEventListener('pointercancel',clear);btn.addEventListener('lostpointercapture',clear)});
$('#action').onclick=act;$('#leave').onclick=leaveRoom;$('#menu-shortcut').onclick=openMenu;$('#map-toggle').onclick=()=>$('#map-panel').hidden=!$('#map-panel').hidden;$('#map-close').onclick=()=>$('#map-panel').hidden=true;document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=()=>{$('#menu').close();travel(b.dataset.travel)});document.querySelectorAll('.close-menu').forEach(b=>b.onclick=()=>$('#menu').close());$('#menu').addEventListener('click',e=>{if(e.target===$('#menu')){const r=$('#menu').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#menu').close()}});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frameId);$('#fallback').hidden=false});
try{try{const saved=JSON.parse(sessionStorage.getItem('lane-return'));if(saved&&Number.isFinite(saved.x)&&Number.isFinite(saved.z)){Object.assign(position,clampPosition(saved.x,saved.z));sessionStorage.removeItem('lane-return');}}catch{}setup()}catch(error){console.error('Street initialization failed',error);$('#loading').hidden=true;$('#fallback').hidden=false}
